CREATE TABLE USERS (
ID VARCHAR(255) PRIMARY KEY,
STUDENT_ID VARCHAR(255) UNIQUE,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
GENDER VARCHAR(64) NOT NULL,
PHONE_NUMBER VARCHAR(64) NOT NULL UNIQUE,
EMAIL VARCHAR(64) NOT NULL UNIQUE,
PASSWORD VARCHAR(64) NOT NULL,
COURSE VARCHAR(64) NOT NULL,
DEPARTMENT VARCHAR(64) NOT NULL,
YEARLEVEL VARCHAR(64) NOT NULL,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE ADMIN(
ID VARCHAR(255) PRIMARY KEY,
STUDENT_ID VARCHAR(255) UNIQUE,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
GENDER VARCHAR(64) NOT NULL,
PHONE_NUMBER VARCHAR(64) NOT NULL UNIQUE,
EMAIL VARCHAR(64) NOT NULL UNIQUE,
PASSWORD VARCHAR(64) NOT NULL,
DEPARTMENT VARCHAR(64) NOT NULL,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)


CREATE TABLE DEPARTMENT(
DEPARTMENT_ID VARCHAR(255) PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(65),
WINDOWS_NUMBER NUMBER,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

CREATE TABLE BATCHES(
BATCH_ID VARCHAR(255) PRIMARY KEY,
DEPARTMENT_ID VARCHAR(255),
BATCH_NAME VARCHAR(64),
MAX_STUDENT INT,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
)


CREATE TABLE BOOKING_DATE(
DATE_ID VARCHAR(255) PRIMARY KEY,
BOOKING_DATE DATE,
CURRENT_QUEUE_NUMBER INT DEFAULT 0,
STATUS VARCHAR(255),
);

CREATE TABLE BOOKINGS (
BOOKING_ID VARCHAR(255) PRIMARY KEY,
USER_ID VARCHAR(255),
DATE_ID VARCHAR(255),
BATCH_ID VARCHAR(255),
QUEUE_NUMBER INT,
BOOKING_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
FOREIGN KEY (DATE_ID) REFERENCES BOOKING_DATE(DATE_ID),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);