-- STUDENT Table (formerly operator)
CREATE TABLE
    STUDENT (
        ID VARCHAR(255) PRIMARY KEY,
        STUDENT_ID VARCHAR(255) UNIQUE,
        FIRST_NAME VARCHAR(100) NOT NULL,
        LAST_NAME VARCHAR(100) NOT NULL,
        GENDER VARCHAR(64) NOT NULL,
        PHONE_NUMBER VARCHAR(64) NOT NULL UNIQUE,
        EMAIL VARCHAR(64) NOT NULL UNIQUE,
        PASSWORD VARCHAR(64) NOT NULL,
        COURSE VARCHAR(64) NOT NULL,
        DEPARTMENT VARCHAR(64) NOT NULL,
        YEARLEVEL VARCHAR(64) NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

-- Operator Table (formerly Admin)
CREATE TABLE
    OPERATOR (
        ID VARCHAR(255) PRIMARY KEY,
        OPERATOR_ID VARCHAR(255) UNIQUE,
        FIRST_NAME VARCHAR(100) NOT NULL,
        LAST_NAME VARCHAR(100) NOT NULL,
        GENDER VARCHAR(64) NOT NULL,
        PHONE_NUMBER VARCHAR(64) NOT NULL UNIQUE,
        EMAIL VARCHAR(64) NOT NULL UNIQUE,
        PASSWORD VARCHAR(64) NOT NULL,
        ROLE ENUM ('staff', 'admin') NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

-- Department Table
CREATE TABLE
    DEPARTMENT (
        DEPARTMENT_ID VARCHAR(255) PRIMARY KEY,
        OPERATOR_ID VARCHAR(255) NOT NULL,
        DEPARTMENT_NAME VARCHAR(65) NOT NULL,
        WINDOWS_NUMBER INT NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

-- Batches Table
CREATE TABLE
    BATCHES (
        BATCH_ID VARCHAR(255) PRIMARY KEY,
        QUEUE_ID VARCHAR(255),
        DEPARTMENT_ID VARCHAR(255),
        BOOKING_DATE DATE,
        YEARLEVEL VARCHAR(64),
        BATCH_NAME VARCHAR(64),
        MAX_STUDENT INT,
        STATUS VARCHAR(64),
        STUDENT_IDS JSON,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

-- Batch Bookings Table
CREATE TABLE
    BOOKING (
        ID VARCHAR(255) PRIMARY KEY,
        STUDENT_ID VARCHAR(255),
        BATCH_ID VARCHAR(255),
        QUEUE_NUMBER INT DEFAULT 0,
        REQUEST_FORM JSON,
        PURPOSE VARCHAR(255),
        STATUS ENUM ('PENDING', 'ACCEPTED', 'REJECTED') NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

CREATE TABLE
    QUEUE_ENTRIES (
        QUEUE_ID VARCHAR(255) PRIMARY KEY,
        BATCH_ID VARCHAR(255) NOT NULL,
        STUDENT_QUEUE JSON,
        STATUS VARCHAR(64),
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

